### ISSUE TITLE
Ruby 2.4.0

### ISSUE THREAD

**Issue by karambol** [ericchapman/ruby_wamp_client#5]
ERROR:  Error installing wamp_client:
        ERROR: Failed to build gem native extension.

    current directory: /home/kiju/.gem/ruby/2.4.0/gems/json-1.8.3/ext/json/ext/generator
/usr/bin/ruby24 -r ./siteconf20161228-16135-vibso9.rb extconf.rb
creating Makefile

current directory: /home/kiju/.gem/ruby/2.4.0/gems/json-1.8.3/ext/json/ext/generator
make "DESTDIR=" clean

current directory: /home/kiju/.gem/ruby/2.4.0/gems/json-1.8.3/ext/json/ext/generator
make "DESTDIR="
compiling generator.c
generator.c: In function ‘generate_json’:
generator.c:861:25: error: ‘rb_cFixnum’ undeclared (first use in this function)
     } else if (klass == rb_cFixnum) {
                         ^
generator.c:861:25: note: each undeclared identifier is reported only once for each function it appears in
generator.c:863:25: error: ‘rb_cBignum’ undeclared (first use in this function)
     } else if (klass == rb_cBignum) {
                         ^
Makefile:241: polecenia dla obiektu 'generator.o' nie powiodły się
make: *** [generator.o] Błąd 1

make failed, exit code 2

**Comment by ericchapman** [comment]
This looks like an error with the "json" gem unable to support Ruby 2.4

https://github.com/rails/rails/issues/27450

There is nothing I can do about this.  You will need to use Ruby 2.3 or wait until the team that owns the json gem fixes it.
