### ISSUE TITLE
JRuby support

### ISSUE THREAD

**Issue by brauliobo** [ericchapman/ruby_wamp_client#7]
I've noticed that nothing happens on a `connection.open` call when jruby is being used. Is there any reason why jruby isn't supported?

**Comment by ericchapman** [comment]
@brauliobo The Ruby WAMP Client Library uses the "websocket-eventmachine-client" Gem for the transport layer by default.  I am going to guess that this GEM does not support JRuby.  I don't do anything in my code that would prevent JRuby from being used.

Do you have "verbose" on?  Are any messages being printed when you run the following?

```ruby
options = {
  uri: 'wss://api.poloniex.com',
  realm: 'realm1',
  verbose: true
}

connection = WampClient::Connection.new(options)

connection.on_disconnect do |reason|
  puts 'disconnected'
  puts reason
end

connection.open
```

**Comment by ericchapman** [comment]
Closing since I don't think this library has a dependency on JRuby and no response from the reporter when asked to assist with debug
